package com.pervasive.sth.exceptions;

/**
 * @brief	This class represents an exception generated by TreasureStatus class
 */
public class TreasureNotFoundYetException extends Exception {

	public  TreasureNotFoundYetException() {
		super();
	}

	public TreasureNotFoundYetException(String msg) {
		super(msg);
	}

	public TreasureNotFoundYetException(String msg, Throwable throwable) {
		super(msg, throwable);
	}

	public TreasureNotFoundYetException(Throwable throwable) {
		super(throwable);
	}
}

